Add more math aliases
makerdao/currency pull request #8
Opened 2020-01-17 08:11 UTC by jparklev

`add`, `sub`, and `mul`

2020-01-17 19:53 UTC, levity approved these changes

2020-01-17 19:58 UTC, levity requested changes
I'm fine with adding more aliases, but this part of the code doesn't allow you to define arbitrary aliases, it just exposes names that are already present in bignumber.js

2020-01-17 22:11 UTC, jparklev commented
doesn't [this reduce fnc](https://github.com/makerdao/currency/blob/3fe87ce80e95e33a3366ac22b0b61cb86b30c450/src/Currency.js#L158) grab every element in the array after the first and alias it to whatever bignumber.js fnc the first refers to? could be a case where i'm missing something really obvious

2020-01-18 02:05 UTC, levity commented
Oh no, you’re totally right, I’m the one with the brain hiccup here, sorry
about that

On Fri, Jan 17, 2020 at 2:11 PM Josh Levine <notifications@github.com>
wrote:

> doesn't this reduce fnc
> <https://github.com/makerdao/currency/blob/3fe87ce80e95e33a3366ac22b0b61cb86b30c450/src/Currency.js#L158>
> grab every element in the array after the first and alias it to whatever
> bignumber.js fnc the first refers to? could be a case where i'm missing
> something really obvious
>
> —
> You are receiving this because your review was requested.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/makerdao/currency/pull/8?email_source=notifications&email_token=AABPJA5EPNOQP53EFRWGQTTQ6IUJPA5CNFSM4KIEM7K2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJJD5HQ#issuecomment-575815326>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABPJA4XKA4RXRUO25WJZJLQ6IUJPANCNFSM4KIEM7KQ>
> .
>

2020-01-18 02:12 UTC, levity approved these changes

2020-01-20 07:01 UTC, merged